/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Production branch (main) - cdfllxxtgguyveowmdis
// Test branch - pbzpqsdjaiynrpjpubai
const DEFAULT_PROJECT_ID = "";
const DEFAULT_SUPABASE_URL = `https://${DEFAULT_PROJECT_ID}.supabase.co`;
const DEFAULT_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.XXXX.XXXX';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
const envAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

function normalizeUrl(url: string): string {
  return url.replace(/\/+$/, '');
}

const resolvedSupabaseUrl = normalizeUrl(envSupabaseUrl && envSupabaseUrl.length > 0
  ? envSupabaseUrl
  : DEFAULT_SUPABASE_URL);

const urlHost = new URL(resolvedSupabaseUrl).hostname;

export const projectId = urlHost.split('.')[0];
export const supabaseUrl = resolvedSupabaseUrl;
export const publicAnonKey = envAnonKey && envAnonKey.length > 0 ? envAnonKey : DEFAULT_ANON_KEY;
