/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_a05c3297 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/cdfllxxtgguyveowmdis/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js";

const getEnv = (keys: string[], fallback = "") => {
  for (const key of keys) {
    const value = Deno.env.get(key);
    if (value && `${value}`.length > 0) {
      return value;
    }
  }
  return fallback;
};

const client = () => createClient(
  getEnv(["SUPABASE_URL", "UPABASE_URL", "VITE_SUPABASE_URL"]),
  getEnv(["SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_KEY", "UPABASE_SERVICE_ROLE_KEY"]),
  {
    db: {
      schema: 'public',
    },
  },
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a05c3297").upsert({
    key,
    value
  });
  if (error) {
    // Log error but don't throw - allows menu to load even if cache fails
    console.error(`[kv_store] Error setting key "${key}":`, error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_a05c3297").select("value").eq("key", key).maybeSingle();
  if (error) {
    console.error(`[kv_store] Error getting key "${key}":`, error.message);
    return null;
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a05c3297").delete().eq("key", key);
  if (error) {
    console.error(`[kv_store] Error deleting key "${key}":`, error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a05c3297").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    console.error(`[kv_store] Error setting multiple keys:`, error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_a05c3297").select("value").in("key", keys);
  if (error) {
    console.error(`[kv_store] Error getting multiple keys:`, error.message);
    return [];
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a05c3297").delete().in("key", keys);
  if (error) {
    console.error(`[kv_store] Error deleting multiple keys:`, error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_a05c3297").select("key, value").like("key", prefix + "%");
  if (error) {
    console.error(`[kv_store] Error getting keys by prefix "${prefix}":`, error.message);
    return [];
  }
  return data?.map((d) => d.value) ?? [];
};
